# Generated by Django 5.0.3 on 2024-03-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendWork', '0002_rename_product_favorite_productid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(to='BackendWork.product'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
