# Generated by Django 5.0.4 on 2024-04-19 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendWork', '0002_alter_user_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='address',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoiceDate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='orderStatus',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='storeId',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='user',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shipping_address',
        ),
        migrations.AddField(
            model_name='address',
            name='line2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_status',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default=('DEFAULT', 'Default'), max_length=9),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shippingAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BackendWork.address'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='aptNum',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('HI', 'Hawaii'), ('PA', 'Pennsylvania'), ('DE', 'Delaware'), ('ME', 'Maine'), ('TN', 'Tennessee'), ('VT', 'Vermont'), ('WI', 'Wisconsin'), ('IN', 'Indiana'), ('KY', 'Kentucky'), ('OK', 'Oklahoma'), ('MS', 'Mississippi'), ('TX', 'Texas'), ('PR', 'Puerto Rico'), ('MP', 'Northern Mariana Islands'), ('UT', 'Utah'), ('AK', 'Alaska'), ('CA', 'California'), ('IL', 'Illinois'), ('MN', 'Minnesota'), ('MI', 'Michigan'), ('CO', 'Colorado'), ('NE', 'Nebraska'), ('WV', 'West Virginia'), ('AR', 'Arkansas'), ('NM', 'New Mexico'), ('MO', 'Missouri'), ('MT', 'Montana'), ('WY', 'Wyoming'), ('NV', 'Nevada'), ('GA', 'Georgia'), ('WA', 'Washington'), ('MD', 'Maryland'), ('AS', 'American Samoa'), ('VA', 'Virginia'), ('ND', 'North Dakota'), ('GU', 'Guam'), ('LA', 'Louisiana'), ('OH', 'Ohio'), ('OR', 'Oregon'), ('IA', 'Iowa'), ('NJ', 'New Jersey'), ('VI', 'Virgin Islands'), ('RI', 'Rhode Island'), ('AL', 'Alabama'), ('NH', 'New Hampshire'), ('CT', 'Connecticut'), ('NY', 'New York'), ('SC', 'South Carolina'), ('AZ', 'Arizona'), ('FL', 'Florida'), ('ID', 'Idaho'), ('DC', 'District of Columbia'), ('KS', 'Kansas'), ('SD', 'South Dakota'), ('MA', 'Massachusetts'), ('NC', 'North Carolina')], max_length=2),
        ),
        migrations.AlterField(
            model_name='productreviews',
            name='rating',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(blank=True, to='BackendWork.product'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_item', to='BackendWork.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendWork.product')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(through='BackendWork.InvoiceItem', to='BackendWork.product'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to=settings.AUTH_USER_MODEL)),
                ('shippingAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BackendWork.address')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='BackendWork.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackendWork.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='BackendWork.OrderItem', to='BackendWork.product'),
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
